import type { Metadata } from "next"
import "./globals.css"
import Header from "@/components/Header"
import { AppContextProvider } from "@/app/AppContext"
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-dvh flex-col">
        <AppContextProvider>
          <Toaster />
          <Header />
          <main className="flex grow px-4">{children}</main>
        </AppContextProvider>
      </body>
    </html>
  )
}
